apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    app: {{ template "td-agent-barito.name" . }}
  name: {{ template "td-agent-barito.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ template "td-agent-barito.name" . }}
        release: {{ .Release.Name }}
      namespace: {{ .Release.Namespace }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/tdagentbaritoconfig.yaml") . | sha256sum }}
    spec:
      serviceAccountName: {{ if .Values.rbac.create }}{{ template "td-agent-barito.fullname" . }}{{ else }}"{{ .Values.rbac.serviceAccountName }}"{{ end }}
      containers:
        - image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: {{ template "td-agent-barito.fullname" . }}
          resources:
            limits:
              memory: {{ .Values.resources.limits.memory }}
              ephemeral-storage: {{ .Values.resources.limits.ephemeral-storage }}
            requests:
              memory: {{ .Values.resources.requests.memory }}
              ephemeral-storage: {{ .Values.resources.requests.ephemeral-storage }}
          volumeMounts:
            - mountPath: /var/log
              name: varlog
            - mountPath: /var/lib/docker/containers
              name: varlibdockercontainers
            - mountPath: /etc/td-agent
              name: td-agent-barito-config
      volumes:
        - hostPath:
            path: /var/log
          name: varlog
        - hostPath:
            path: /var/lib/docker/containers
          name: varlibdockercontainers
        - name: td-agent-barito-config
          configMap:
            name: {{ template "td-agent-barito.fullname" . }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
      {{- end }}
