apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "td-agent-barito.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  td-agent.conf: |
    <source>
      @type tail
      path /var/log/containers/*.log
      pos_file /var/log/fluentd-containers.log.pos
      time_format %Y-%m-%dT%H:%M:%S.%NZ
      tag kubernetes.*
      <parse>
        {{- if .Values.useCRIFormat }}
        @type regexp
        expression /^(?<time>.+) (?<stream>std(?:out|err)) (?<flag>[FP]) (?<message>.*)$/
        time_key time
        time_format %Y-%m-%dT%H:%M:%S.%N%:z
        {{- else }}
        @type none
        {{- end }}
      </parse>
      read_from_head true
    </source>

    <filter kubernetes.**>
      @type kubernetes_metadata
      de_dot false
    </filter>

    {{- range .Values.apps }}
    <match kubernetes.var.log.containers.{{ .name }}-**.log>
      @type barito_batch_k8s
      name {{ .name }}
      cluster_name {{ $.Values.cluster_name }}
      application_name {{ .baritoAppName }}
      {{- if .applicationGroupSecret }}
      application_group_secret {{ .applicationGroupSecret }}
      {{- else }}
      application_group_secret {{ $.Values.defaultAppOptions.applicationGroupSecret }}
      {{- end }}
      {{- if .produceUrl }}
      produce_url {{ .produceUrl }}
      {{- else }}
      produce_url {{ $.Values.defaultAppOptions.produceUrl }}
      {{- end }}
      <buffer>
        flush_at_shutdown {{ $.Values.defaultAgentOptions.buffer.flushAtShutdown }}
        flush_thread_count {{ $.Values.defaultAgentOptions.buffer.flushThreadCount }}
        flush_thread_interval {{ $.Values.defaultAgentOptions.buffer.flushThreadInterval }}
        flush_thread_burst_interval {{ $.Values.defaultAgentOptions.buffer.flushThreadBurstInterval }}
        flush_mode {{ $.Values.defaultAgentOptions.buffer.flushMode }}
        flush_interval {{ $.Values.defaultAgentOptions.buffer.flushInterval }}
        queued_chunks_limit_size {{ $.Values.defaultAgentOptions.buffer.queuedChunksLimitSize }}
        overflow_action {{ $.Values.defaultAgentOptions.buffer.overflowAction }}
        retry_timeout {{ $.Values.defaultAgentOptions.buffer.retryTimeout }}
        retry_max_times {{ $.Values.defaultAgentOptions.buffer.retryMaxTimes }}
        retry_type {{ $.Values.defaultAgentOptions.buffer.retryType }}
        retry_wait {{ $.Values.defaultAgentOptions.buffer.retryWait }}
        retry_exponential_backoff_base {{ $.Values.defaultAgentOptions.buffer.retryExponentialBackoffBase }}
        disable_chunk_backup {{ $.Values.defaultAgentOptions.buffer.disableChunkBackup }}
        {{- range .bufferOptions }}
        {{ . }}
        {{- end }}
      </buffer>
    </match>
    {{- end }}
