image:
  name: barito/td-agent-barito-kubernetes
  tag: latest
  pullPolicy: Always
tolerations: []
nodeSelector: {}
affinity: {}

rbac:
  ## If true, create and use RBAC resources
  create: false
  ## Ignored if rbac.create is true
  serviceAccountName: default

resources:
  limits:
    cpu: 2
    memory: 2Gi
    ephemeralStorage: 6Gi
  requests:
    cpu: 500m
    memory: 1Gi
    ephemeralStorage: 4Gi

defaultAgentOptions:
  buffer:
    flushAtShutdown: true
    flushThreadCount: 8
    flushThreadInterval: 1.0
    flushThreadBurstInterval: 1.0
    flushMode: interval
    flushInterval: 1s
    queuedChunksLimitSize: 1
    overflowAction: drop_oldest_chunk
    retryTimeout: 0s
    retryMaxTimes: 3
    retryType: exponential_backoff
    retryWait: 1s
    retryExponentialBackoffBase: 2
    disableChunkBackup: true

useCRIFormat: false
preMatchConfig: ""
postMatchConfig: ""
  #     <source>
  #       @type tail
  #       path           /var/log/messages
  #       pos_file       /var/log/messages.pos
  #       read_from_head true
  #       tag            syslog
  #       <parse>
  #         @type regexp
  #           expression  ^(?<time>[^ ]*.+[^ ]* [^ ]*) (?<host>[^ ]*) (?<process>[^ ]*): (?<message>.*)$
  #           time_format %b  %d %H:%M:%S
  #           time_key    time
  #       </parse>
  #     </source>

  #     <match syslog>
  #       @type stdout
  #     </match>

# Any extra volumes
extraVolumes: []
  # - name: example-name
  #   hostPath:
  #     path: /path/on/host
  #     type: DirectoryOrCreate
  # - name: ssl-certs
  #   hostPath:
  #     path: /etc/ssl/certs/ca-bundle.crt

# Any extra volume mounts
extraVolumeMounts: []
  #   - name: example-name
  #     mountPath: /path/in/container
  #   - name: ssl-certs
  #     mountPath: /etc/ssl/certs/ca-certificates.crt
  #     readOnly: true

priorityClassName: ""
livenessProbe:
  initialDelaySeconds: 10
  timeoutSeconds: 10
